[theme.custom]
panel_bg = "#1d2021"
surface0 = "#3c3836"
surface1 = "#504945"
surface_dim = "#3c3836"
active_row_bg = "#3c3836"
selection_bg = "#3c3836"
overlay0 = "#928374"
overlay1 = "#d5c4a1"
text = "#ebdbb2"
subtext0 = "#bdae93"
accent = "#458588"
mauve = "#d3869b"
green = "#98971a"
yellow = "#d79921"
red = "#cc241d"
blue = "#458588"
teal = "#689d6a"
peach = "#fe8019"
