[theme.custom]
panel_bg = "#1f1f28"
surface0 = "#2a2a37"
surface1 = "#363646"
surface_dim = "#2a2a37"
active_row_bg = "#2a2a37"
selection_bg = "#2a2a37"
overlay0 = "#727169"
overlay1 = "#c8c093"
text = "#dcd7ba"
subtext0 = "#c8c093"
accent = "#7e9cd8"
mauve = "#957fb8"
green = "#76946a"
yellow = "#c0a36e"
red = "#c34043"
blue = "#7e9cd8"
teal = "#6a9589"
peach = "#e6c384"
