[theme.custom]
panel_bg = "#111318"
surface0 = "#333842"
surface1 = "#4f5666"
surface_dim = "#333842"
overlay0 = "#c5cad3"
overlay1 = "#c5cad3"
text = "#c5cad3"
subtext0 = "#c5cad3"
accent = "#42b3c2"
mauve = "#c162de"
green = "#8cc265"
yellow = "#d18f52"
red = "#e05561"
blue = "#4aa5f0"
teal = "#42b3c2"
peach = "#f0a45d"
