# vim:fileencoding=utf-8:foldmethod=marker

# Basics

## Foreground and background
foreground #abb2bf
background #111318

## Selection foreground and background
selection_foreground #000000
selection_background #82868c

## Cursor and url
cursor #abb2bf
url_color #61afef

## Tabs
active_tab_foreground   #1e2127
active_tab_background   #89ca78
inactive_tab_foreground #89ca78
inactive_tab_background #1e2127

# Color Scheme

# Black
color0 #1e2127
color8 #5c6370

# Red
color1 #ef596f
color9 #ef596f

# Green
color2  #89ca78
color10 #89ca78

# Yellow
color3  #d19a66
color11 #d19a66

# Blue
color4  #61afef
color12 #61afef

# Magenta
color5  #d55fde
color13 #d55fde

# Cyan
color6  #2bbac5
color14 #2bbac5

# White
color7  #abb2bf
color15 #abb2bf
