#!/usr/bin/env bash

# Layout
yabai -m config layout stack
yabai -m config window_placement second_child

# Padding
yabai -m config top_padding    7
yabai -m config bottom_padding 7
yabai -m config left_padding   7
yabai -m config right_padding  7
yabai -m config window_gap     7

# Mouse support
yabai -m config mouse_modifier alt
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on

# Disable for specific apps
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^FortiClientVPN$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Terminal$" manage=off
yabai -m rule --add app="^TextEdit$" manage=off
yabai -m rule --add app="WhatsApp" manage=off
