# dump
# Autogenerated from man page /usr/share/man/man1/dump.erofs.1.gz
complete -c dump -l device -d 'Specify an extra device to be used together'
complete -c dump -l nid -d 'Specify an inode NID in order to print its file information'
complete -c dump -s e -d 'Show the file extent information'
complete -c dump -s V -d 'Print the version number and exit'
complete -c dump -s s -d 'Show superblock information of the an EROFS-formatted image'
complete -c dump -s S -d 'Show EROFS disk statistics, including file type/size distribution, number of …'

