[mgr]
border_symbol = " "
count_copied   = { fg = "green", bg = "reset" }
count_cut      = { fg = "red", bg = "reset" }
count_selected = { fg = "yellow", bg = "reset" }

[indicator]
preview = { reversed = true }

[tabs]
active   = { fg = "black", bg = "magenta", bold = true }
inactive = { fg = "magenta", bg = "black" }

[mode]
normal_main = { fg = "cyan", bg = "reset", bold = true }
normal_alt  = { fg = "green", bg = "reset" }
select_main = { fg = "yellow", bg = "reset", bold = true }
select_alt  = { fg = "yellow", bg = "reset" }
unset_main = { fg = "magenta", bg = "reset", bold = true }
unset_alt  = { fg = "magenta", bg = "reset" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }
progress_normal = { fg = "green", bg = "reset" }
progress_error  = { fg = "red", bg = "reset" }

[confirm]
btn_labels = [" Yes ", " No "]
