[directory]
style = 'bold blue'
read_only = ' 󰌾'
truncation_length = 50

[cmd_duration]
format = '[$duration]($style) '

[status]
disabled = false
format = '[$symbol $status]($style) '
symbol = '󰅚'
not_executable_symbol = '󰜺'
not_found_symbol = ''
sigint_symbol = '󱘖'
signal_symbol = '󱐋'
map_symbol = true

[git_branch]
format = '[$symbol$branch]($style) '
symbol = ' '

[package]
format = '[$symbol$version]($style) '
symbol = ' '

[docker_context]
format = '[$symbol]($style) '
symbol = ' '

[nodejs]
format = '[$symbol($version )]($style)'
symbol = ' '

[dotnet]
format = '[$symbol($version )(󰓾 $tfm )]($style)'
symbol = '󰪮 '

[golang]
format = '[$symbol($version )]($style)'
symbol = ' '

[lua]
format = '[$symbol($version )]($style)'
symbol = ' '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
