[colors.bright]
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#d19a66"

[colors.dim]
black = "#1e2127"
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#d19a66"

[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#111318"
bright_foreground = "#e6efff"
foreground = "#abb2bf"

[cursor.style]
blinking = "Never"
shape = "Beam"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove Nerd Font"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000

[window]
opacity = 0.975

[window.padding]
x = 4
y = 4
